FROM node:22-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

EXPOSE 5173
CMD ["pnpm", "run", "dev", "--", "--host"]